### ISSUE TITLE
Can not compile the repo

### ISSUE THREAD

**Issue by wz14** [BitVM/BitVM#78]
rust version: 1.79.0-nightly
os: macos 13.2.1

After running uint test `test_groth16_verifier`, some error happened.
```
error[E0599]: no method named `modinv` found for struct `num_bigint::BigUint` in the current scope
   --> src/fflonk/compute_c_wi.rs:131:23
    |
131 |         let r_inv = r.modinv(&h).unwrap();
    |                       ^^^^^^
    |
help: there is a method `div` with a similar name
    |
131 |         let r_inv = r.div(&h).unwrap();
    |                       ~~~
```

It seems that we can not use modinv with num-bigint 0.4.4. After I update to 0.4.6, it works well.

But there are some more errors.

```

error[E0277]: the trait bound `bitcoin::XOnlyPublicKey: treepp::pushable::Pushable` is not satisfied
   --> src/bridge/transactions.rs:281:9
    |
281 |         { n_of_n_pubkey }
    |         ^^^^^^^^^^^^^^^^^ the trait `treepp::pushable::NotU8Pushable` is not implemented for `bitcoin::XOnlyPublicKey`, which is required by `bitcoin::XOnlyPublicKey: treepp::pushable::Pushable`
    |
    = help: the trait `treepp::pushable::Pushable` is implemented for `u8`
note: required for `bitcoin::XOnlyPublicKey` to implement `treepp::pushable::Pushable`
   --> src/lib.rs:7:5
    |
7   |     define_pushable!();
    |     ^^^^^^^^^^^^^^^^^^
note: required by a bound in `generate_pre_sign_script::{closure#0}::push`
   --> src/bridge/transactions.rs:281:9
    |
281 |         { n_of_n_pubkey }
    |         ^^^^^^^^^^^^^^^^^ required by this bound in `push`
    = note: this error originates in the macro `define_pushable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `enforce_stack_limit` on type `bitcoin_scriptexec::Options`
   --> src/lib.rs:142:10
    |
142 |     opts.enforce_stack_limit = false;
    |          ^^^^^^^^^^^^^^^^^^^ unknown field
```

**Comment by lucidLuckylee** [comment]
Hey, I cannot reproduce this with the latest commit. Make sure to run `cargo update`

**Comment by wz14** [comment]
> Hey, I cannot reproduce this with the latest commit. Make sure to run `cargo update`

Thanks! Need to update dependency manually.
